spring:
  jpa:
    database: H2
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    datasource:
      url: jdbc:h2:mem:pokemong-tcg
      username: sa
      password: password
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /stabulith/v1
  port: '8080'